# Generated by Django 3.2 on 2021-04-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('user', models.CharField(max_length=30, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=100, verbose_name='密码')),
            ],
        ),
    ]
