# Generated by Django 3.2 on 2021-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='department',
            field=models.CharField(default='null', max_length=100, verbose_name='科室'),
            preserve_default=False,
        ),
    ]
