# Generated by Django 3.2 on 2021-04-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_doctors_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='department',
            field=models.IntegerField(max_length=100, verbose_name='科室'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
