# Generated by Django 3.2 on 2021-04-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_auto_20210413_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
