# Generated by Django 3.2 on 2021-04-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_auto_20210413_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
