# Generated by Django 3.2 on 2021-04-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20210418_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outpatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('Uid', models.IntegerField(verbose_name='患者编号')),
                ('Did', models.IntegerField(verbose_name='医生编号')),
                ('diagnosis', models.TextField(verbose_name='诊断建议')),
                ('Otime', models.DateTimeField(auto_now_add=True, verbose_name='就诊时间')),
            ],
        ),
    ]
