# Generated by Django 3.2 on 2021-04-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_outpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='EDid',
        ),
    ]
