# Generated by Django 3.2 on 2021-04-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_remove_examination_edid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physiological',
            old_name='Pinformation',
            new_name='Physiological',
        ),
        migrations.AlterField(
            model_name='therapy',
            name='Did',
            field=models.IntegerField(verbose_name='医生编号'),
        ),
    ]
